
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: rafael
  password: raf1234
  host: localhost


development:
  <<: *default
  database: task_manager_development

 
test:
  <<: *default
  database: task_manager_test

production:
  primary: &primary_production
    <<: *default
    database: task_manager_production
    username: task_manager
    password: <%= ENV["TASK_MANAGER_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: task_manager_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: task_manager_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: task_manager_production_cable
    migrations_paths: db/cable_migrate
